services:

  db:
    image: mysql:8.0
    container_name: magic-investor-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD_MAGIC.sql:/docker-entrypoint-initdb.d/BD_MAGIC.sql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - proxy


  backend:
    image: investor-api-backend:latest
    container_name: magic-investor-backend
    restart: unless-stopped

    environment:
      CARDTRADER_API_TOKEN: ${CARDTRADER_API_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 8080

    depends_on:
      db:
        condition: service_healthy

    networks:
      - proxy


  frontend:
    image: investor-api-frontend:latest
    container_name: magic-investor-frontend
    restart: unless-stopped

    depends_on:
      - backend

    networks:
      - proxy


volumes:
  mysql_data:


networks:
  proxy:
    external: true